language: ruby
services:
  - redis-server
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'create database www_rails_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
notifications:
  slack:
    secure: Qi3NqgqqtUb2Sap9LGHphz5achbAOavYke/AgtYgGrrk7qL0EYUmS74quTb4ciWzse/ig4vT5mbBaqLN1hYchK4RUdjBqu9X4VTUsFpHajZ556rXaiws96wbyasvB6/KZrsi/hhJlil7Q1G4SUEJE9Xx3HMBWOtXu0YDMmGhioL50TuPICY+vGLkiYVvvq47YBqHEyW4ZL0PP9rWxA96tPLMwXvK3PjywfZ0yhN0pO9V9d94sCEZ5puTlK6x5Hv6qNJRwLoOwqOGlEExcc0tJ1N/+kRGNAYdJhRILtqNQqybcnfQarezB02CurEmnnSqaSxrcpwA6fgmA18+CaFXF9708c6icb7qe508RruJ7wttfz8HBR/IbnHEvGltd7eKVfH210jlZSBSOcWrrZX5hgAMqKH8sBzLMW8KNUXLgE7iH+C0vlz4RrzNWPL73Kfx4JK3GZwpoW1XB2ssuek65OVwqMXSpsLhLMdc0rwoQgjIAqKKGYrqvNK+438Os4lbsSOyP6OEOM0u2xC4AdoOWWXKTX7kO3hfk249HX5Uih20sBgQ6dqDGeW0tCfdpBe/ocyE+7eQZcVJ5wqbIJtf47qbxyGx/7/D8kR4rN8FJ+9TFz4ysS6C8DRlBIvJvMFd3825ikYIWSVmhrJ4zdTX4zbQe22Mf8LMvBcA8lYLNqE=
env:
  global:
    # CLOUDINARY_URL + ALUMNI_WWW_SHARED_SECRET + MAILGUN_PUBLIC_API_KEY + MAILCHIMP_API_KEY + MAILCHIMP_LIST_ID
    secure: "kXquN8OBGwneh+eNoxdgCXZQYHAuvbau36GdpSGXetuqLVtsgyfdfbUM7Ppl/eK1CRWFJ9t8UgaJTXEwXvHrQiDvBPjQZy6m4VWBH/nkq02KrTBj+6z8vUz7FFRofO8akcepXTSgltBdY3dv64gd9mKq2fbuOD+o4nweOpZb2AqRyft7ZiCj+1nqRu7MwFykZ8KxLOK0DrWFuPc3XrgDoC0acoRLqTE7Skq/0jRNZ6u/Y8bmcnViL3eNF1WBUdgv+6wxzsFZiBWbW+OLLVP2EGlwjXGO5V4CT4PYP9HBwgCHW9H/u+zaQL+YirSXfLXtam6zwiuWbnE8uuR7TlWCjJ+MSil1DfzeczwhUnR6Z2rrVmOvO7uEQnzFd5Ot1mIBn7MPMwWkJL53kG84XBjANCQxiMDTkl83nFhRnzBFlKwBnJ9CSkR8ekckOl6ex6oHZZ+5Mxe5JFCxkYMtULNu4u3XDC1I6y6jqLQgI/3IJ+yDN2EZurTPLJUCp1y7U7y1UUN3G9Z3LCO257LzY2n6VUPWtgP/AU5huKEDEEkhtuckA+e82n2oCcM/sv5WWiI6QzGXLbo3UOWseHV2jEXozGPCgrrPv/GbKgq6cnE/+MfzolJINr18N69jhoCCNOcpSbJ9EEvJSAKRDqqsH3Y6sdBJedmfoy4+Djy9S734XsM="
