thanks:
  en: thanks
  fr: merci
  pt-BR: obrigado
  es: gracias
  zh-CN: 谢谢
  ja: ありがとう
program:
  en: program
  fr: programme
  pt-BR: programa
  es: temario
  zh-CN: 程序
  ja: プログラム
press:
  en: press
  fr: presse
  pt-BR: imprensa
  es: prensa
  zh-CN: 媒体
  ja: プレス
about:
  en: about
  fr: a-propos
  pt-BR: sobre
  es: quienes-somos
  zh-CN: 关于
  ja: 私たちに関しては

