thanks:
  en: thanks
  fr: merci
  pt-BR: obrigado
program:
  en: program
  fr: programme
  pt-BR: programa
press:
  en: press
  fr: presse
  pt-BR: imprensa
about:
  en: about
  fr: a-propos
  pt-BR: o-que-e
